config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  root to: 'homes#top'
  devise_scope :user do
    post '/users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :users, only: [:index, :show, :edit, :update, :destroy]
  resources :games, only: [:index, :show, :create, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :game_comments, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/game.rb
class Game < ApplicationRecord
  attachment :game_image
  belongs_to :user
  has_many :game_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  validates :title, presence: true
  validates :hard, presence: true
  validates :body, presence: true
end

app/models/game_comment.rb
class GameComment < ApplicationRecord
  belongs_to :user
  belongs_to :game
  
  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.name = "ゲストユーザー（閲覧専用）"
      user.password = SecureRandom.urlsafe_base64
      # user.confirmed at = Time.now
    end
  end
  has_many :games, dependent: :destroy
  has_many :game_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  validates :name, length: {in: 2..20}
  validates :introduction, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    game = Game.find(params[:game_id])
    favorite = current_user.favorites.new(game_id: game.id)
    if current_user.email == 'guest@example.com'
      flash[:notice] = 'ゲストユーザーはいいねできません。'
      redirect_to game_path(game)
    else
      favorite.save
      redirect_to game_path(game)
    end
  end

  def destroy
    game = Game.find(params[:game_id])
    favorite = current_user.favorites.find_by(game_id: game.id)
    favorite.destroy
    redirect_to game_path(game)
  end
end

app/controllers/game_comments_controller.rb
class GameCommentsController < ApplicationController
  def create
    game = Game.find(params[:game_id])
    comment = current_user.game_comments.new(game_comment_params)
    comment.game_id = game.id
    if current_user.email == 'guest@example.com'
      flash[:notice] = 'ゲストユーザーはコメントできません。'
      redirect_to game_path(game)
    elsif comment.save
      flash[:notice] = "コメント投稿されました！"
      redirect_to game_path(game)
    else
      flash[:notice] = "エラー：コメント内容を入力して下さい"
      redirect_to game_path(game)
    end
  end
  
  def destroy
    GameComment.find_by(id: params[:id]).destroy
    redirect_to game_path(params[:game_id])
  end
  
  private
  
  def game_comment_params
    params.require(:game_comment).permit(:comment)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @user = current_user
    @game = Game.new
    @games = Game.page(params[:page]).reverse_order
  end

  def create
    @user = current_user
    @games = Game.page(params[:page]).reverse_order
    @game = Game.new(game_params)
    @game.user_id = current_user.id
    if @user.email == 'guest@example.com'
      flash[:notice] = 'ゲストユーザーは投稿できません。'
      redirect_to games_path
    elsif @game.save
      flash[:notice] = "新規投稿されました！"
      redirect_to game_path(@game.id)
    else
      render :index
    end
  end

  def show
    @game = Game.find(params[:id])
    @user = @game.user
    @game_new = Game.new
    @game_comment = GameComment.new
  end

  def destroy
    game = Game.find(params[:id])
    game.destroy
    redirect_to games_path
  end
  
  private
  
  def game_params
    params.require(:game).permit(:title, :hard, :game_image, :body, :user_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  before_action :check_guest, only: :create
  def check_guest
    if params[:user][:email].downcase == 'guest@example.com'
      redirect_to new_user_session_path, alert: 'ゲストユーザーのパスワード再設定はできません。'
    end
  end
  
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :check_guest, only: %i[update destroy]
  
  def check_guest
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーの更新・削除はできません。'
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to games_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = current_user
    @game = Game.new
    @users = User.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @game = Game.new
    @games = @user.games.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
    if @user.id == current_user.id
      render :edit
    else
      redirect_to current_user
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.email == 'guest@example.com'
      flash[:notice] = 'ゲストユーザーの編集はできません。'
      redirect_to games_path
    elsif @user.update(user_params)
      flash[:notice] = "ユーザー情報を更新しました！"
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    if @user.email == 'guest@example.com'
      flash[:notice] = 'ゲストユーザーの削除はできません。'
      redirect_to games_path
    else
      @user.destroy
      flash[:notice] = 'ユーザー削除しました。またのご利用をお待ちしております！'
      redirect_to root_path
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/game_comments_helper.rb
module GameCommentsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/_game_index.html.erb
        <h2>投稿一覧</h2>
        <div class="card-list-container mx-auto pb-5">
          <% games.each do |game| %>
            <div class="card mb-4 shadow-lg">
              <div class="game-item">
                <div>
                  <%= link_to game_path(game.id) do %>
                    <%= attachment_image_tag game, :game_image, :fill, 100, 100, format: "jpeg", fallback: "default-image.jpg", class:"w-200 ml-0 border-radius utilities img-thumbnail" %>
                  <% end %>
                </div>
                <div class="game-title">
                  ゲーム名：<%= link_to "#{game.title}", game_path(game.id) %><br>
                  ゲーム機種：<%= game.hard %>
                </div>
              </div>
              <div class="card-body pl-0 pb-0">
                <div>
                  【ゲーム説明】<br>
                  <%= safe_join(game.body.split("\n"),tag(:br)) %>
                </div>
                <span>
                  <%= link_to user_path(game.user.id) do %>
                    <%= attachment_image_tag game.user, :profile_image, :fill, 60, 60, format: "jpeg", fallback: "no_image.jpg" %>
                    <br/>
                    By <%= game.user.name %> ｜
                  <% end %>
                </span>
                <span><%= link_to "#{game.game_comments.count} コメント", game_path(game.id) %> ｜</span>
                <% if game.favorited_by?(current_user) %>
                  <span>
                    <%= link_to game_favorites_path(game), method: :delete do %>
                      ♥<%= game.favorites.count %> いいね
                    <% end %>
                  </span>
                <% else %>
                  <span>
                    <%= link_to game_favorites_path(game), method: :post do %>
                      ♡<%= game.favorites.count %> いいね
                    <% end %>
                  </span>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
        <%= paginate games %>
       
      

app/views/games/index.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class='container px-5 px-sm-0'>
    <% if @game.errors.any? %>
      <%= @game.errors.count %>件のエラーにより、この投稿を保存できませんでした
      <ul>
        <% @game.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    <div class='row'>
      <%= render "users/user_info", user: @user, game: @game %>
      <div class='col-lg-7 offset-lg-1'>
        <%= render "games/game_index", games: @games, game: @game %>
      </div>
    </div>
  </div>
</main>

app/views/games/show.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class='container px-5 px-sm-0'>
    <div class='row'>
      <%= render "users/user_info2", user: @user, game: @game_new %>
      <div class='col-lg-7 offset-lg-1'>
        <h2>投稿詳細及びコメント</h2>
        <div class="card mb-4 shadow-lg">
          <div class="game-item">
            <div>
              <%= link_to game_path(@game.id) do %>
                <%= attachment_image_tag @game, :game_image, :fill, 100, 100, format: "jpeg", fallback: "default-image.jpg", class:"w-200 ml-0 border-radius utilities img-thumbnail" %>
              <% end %>
            </div>
            <div class="game-title">
              ゲーム名：<%= @game.title %><br>
              ゲーム機種：<%= @game.hard %>
            </div>
          </div>
          <div class="card-body pl-0 pb-0">
            <div>
              【ゲーム説明】<br>
              <%= safe_join(@game.body.split("\n"),tag(:br)) %>
            </div>
            <div>
              <% if @game.user.id == current_user.id %>
                <%= link_to "投稿削除", game_path(@game.id), method: :delete, class:"btn btn-sm btn-danger destroy", "data-confirm" => "本当に消しますか？" %>
              <% end %>
            </div>
            <% if @game.favorited_by?(current_user) %>
              <span>
                <%= link_to game_favorites_path(@game), method: :delete do %>
                  ♥<%= @game.favorites.count %> いいね
                <% end %>
              </span>
            <% else %>
              <span>
                <%= link_to game_favorites_path(@game), method: :post do %>
                  ♡<%= @game.favorites.count %> いいね
                <% end %>
              </span>
            <% end %>
          </div>
          <hr>
      　　<div class="comments card-text">
            <h4 class="mt-3">【コメント件数：<%= @game.game_comments.count %>】</h4>
            <% @game.game_comments.each do |game_comment| %>
              <div class="media border mb-3">
                <div>
                  <%= link_to user_path(game_comment.user.id) do %>
                    <%= attachment_image_tag game_comment.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", class:"bd-placeholder-img align-self-center mx-3" %><br>
                    <%= game_comment.user.name %>
                  <% end %>
                </div>
                <div>
                  <%= safe_join(game_comment.comment.split("\n"),tag(:br)) %>
                  <br>
                  <% if game_comment.user == current_user %>
                    <%= link_to "コメント削除", game_game_comment_path(game_comment.game, game_comment), method: :delete, class:"btn btn-sm btn-danger destroy", "data-confirm" => "本当に消しますか？"  %>
                  <% end %>
                </div>
              </div>  
            <% end %>
          </div>
          <hr>
          <div class="new-comment card-text">
            <%= form_with(model:[@game, @game_comment], local: true) do |f| %>
              <div class="form-group">
                <label for="exampleFormControlTextarea1">コメントする</label>
                <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
              </div>
              <%= f.submit "送信する", class:"btn btn-lg btn-info mt-2 float-right" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <div class="jumbotron jumbotron-fluid mb-0">
    <p id="notice"><%= flash[:notice] %></p>
    <div class="container">
      <div class="row">
        <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
          <div>
            <h1 class="toppage-title font-weight-bold">
              ようこそ<br>
              ゲームマニアへ！！
            </h1>
            <p class="toppage-overview font-weight-bold">
              ここはレトロゲームや最新ゲームを問わず</br>
              ゲーム好きな人達が熱く語り合う場です。
            </p>
          </div>
          <div class="btn-wrapper col-10 mx-auto">
            <div class="row">
              <a class="btn btn-info btn-sm btn-block mb-3" href="/users/sign_in">ログイン</a>
            </div>
            <div class="row">
              <a class="btn btn-success btn-sm btn-block mb-3" href="/users/sign_up">ユーザー登録</a>
            </div>
            <div class="row">
              <a class="btn btn-primary btn-sm btn-block" data-method="post" href="/users/guest_sign_in">ゲストログイン（閲覧用）</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/_header.html.erb
<header class="sticky-top">
  <nav class="navbar navbar-expand-lg navbar-dark bg-danger">
    <div class="container">
      <a class="navbar-brand" href="/">
        <span>ゲームマニア</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li>
              <a class="nav-link text-light" href="/users/<%= current_user.id %>">
                <i class="fas fa-home"></i>マイページ
              </a>
            </li>
            <li>
              <a class="nav-link text-light" href="/users">
                <i class="fas fa-users"></i>ユーザー一覧
              </a>
            </li>
            <li>
              <a class="nav-link text-light" href="/games">
                <i class="fas fa-book-open"></i>投稿一覧
              </a>
            </li>
            <li>
              <a class="nav-link text-light" rel="nofollow" data-method="delete" href="/users/sign_out">
                <i class="fas fa-sign-out-alt"></i>ログアウト
              </a>
            </li>
          <% else %>
            <li>
              <a class="nav-link text-light" href="/">
                <i class="fas fa-home"></i>Home
              </a>
            </li>
            <li>
              <a class="nav-link text-light" href="/users/sign_up">
                <i class="fas fa-user-plus"></i>ユーザー登録
              </a>
            </li>
            <li>
              <a class="nav-link text-light" href="/users/sign_in">
                <i class="fas fa-sign-in-alt"></i>ログイン
              </a>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameMania</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/users/_user_info.html.erb
      <div class='col-lg-4'>
        <h2>ユーザー情報</h2>
        <table class='table'>
          <tr>
            <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: "jpeg", fallback: "no_image.jpg" %>
          </tr>
          <tr>
            <th>名前</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>
              自己<br>
              紹介
            </th>
            <th><%= user.introduction %></th>
          </tr>
        </table>
        <div class='row'>
          <a class="btn btn-outline-secondary btn-block" href="/users/<%= user.id %>/edit">
            <i class="fas fa-user-cog"></i>
          </a>
        </div>
        <hr>
        <div class="form-body border border-dark p-2">
          <h5 class="text-dark py-4 mb-0">新規投稿フォーム</h5>
          <%= form_with model:game, local:true do |f| %>
            <div class="input-group my-3">
              <label for="game_title">ゲーム名<br>
                <%= f.text_field :title %>
              </label>
            </div>
            <div class="input-group my-3">
              <label for="game_hard">ゲーム機種<br>
                <%= f.select :hard,[["パソコン","パソコン"],["ファミリーコンピューター","ファミリーコンピューター"],["PCエンジン","PCエンジン"],["メガドライブ","メガドライブ"],["ゲームボーイ","ゲームボーイ"],["スーパーファミコン","スーパーファミコン"],["ゲームギア","ゲームギア"],["ネオジオ","ネオジオ"],["PlayStation","PlayStation"],["セガサターン","セガサターン"],["NINTENDO64","NINTENDO64"],["ドリームキャスト","ドリームキャスト"],["ネオジオポケット","ネオジオポケット"],["ワンダースワン","ワンダースワン"],["PlayStation2","PlayStation2"],["ゲームボーイアドバンス","ゲームボーイアドバンス"],["ニンテンドーゲームキューブ","ニンテンドーゲームキューブ"],["Xbox","Xbox"],["ニンテンドーDS","ニンテンドーDS"],["PlayStation Portable","PlayStation Portable"],["Wii","Wii"],["PlayStation3","PlayStation3"],["ニンテンドー3DS","ニンテンドー3DS"],["WiiU","WiiU"],["PlayStation Vita","PlayStation Vita"],["PlayStation4","PlayStation4"],["Nintendo Swich","Nintendo Swich"],["PlayStation5","PlayStation5"],["スマートフォン","スマートフォン"],["その他","その他"]], include_blank: "選択して下さい" %>
              </label>
            </div>
            <div class="input-group my-3">
              <label>ゲーム画像
                <%= f.attachment_field :game_image, placeholder: "ゲーム画像" %>
              </label>
            </div>
            <div class="input-group my-3">
              <label for="input-group-text">ゲーム説明<br>
                <%= f.text_area :body, size: "30x10" %>
              </label>
            </div>
            <div class="form-group">
              <%= f.submit "新規投稿", class:"btn btn-success" %>
            </div>
          <% end %>
        </div>
        <hr>
      </div>

app/views/users/_user_info2.html.erb
      <div class='col-lg-4'>
        <h2>ユーザー情報</h2>
        <table class='table'>
          <tr>
            <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: "jpeg", fallback: "no_image.jpg" %>
          </tr>
          <tr>
            <th>名前</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>
              自己<br>
              紹介
            </th>
            <th><%= user.introduction %></th>
          </tr>
        </table>　 
        <div class='row'>
          <a class="btn btn-outline-secondary btn-block" href="/users/<%= user.id %>/edit">
            <i class="fas fa-user-cog"></i>
          </a>
        </div>
        <hr>
      </div>

app/views/users/edit.html.erb
<div class="jumbotron jumbotron-fluid py-2 mb-0">
  <div class="container">
    <div class="row no-gutters">
      <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto text-center shadow-lg rounded px-0 m-0">
        <h5 class="text-dark bg-light py-4 mb-0">プロフィール編集</h5>
        <div class="form-body bg-light p-4">
          <% if @user.errors.any? %>
            <%= @user.errors.count %>件のエラーにより、変更を保存できませんでした
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
          <%= form_with model:@user, local:true do |f| %>
            <div class="input-group bg-light mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text" aria-hidden="true"><i class="fas fa-user"></i></span>
              </div>
              <%= f.text_field :name, autofocus: true, class:"form-control",id:"inputName", placeholder:"名前" %>
            </div>
            <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback:"no_image.jpg", class:"mb-3" %>
            <div class="input-group bg-light my-3">
              <label>
                <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
              </label>
            </div>
            <div class="input-group bg-light mb-3">
              <span class="input-group-text">自己紹介</span>
              <%= f.text_area :introduction, autofocus: true, class:"form-control", id:"inputBody", placeholder:"自己紹介をここに記入" %>
            </div>
            <div>
              <%= f.submit "変更を保存", class:"btn btn-lg btn-block btn-info mt-5" %>
            </div>
          <% end %>
          <hr>
          <p>
            ユーザー削除を希望の方は、
            <br>下の「ユーザー削除ボタン」を押して下さい。
          </p>
          <%= link_to "ユーザー削除", user_path(@user.id), method: :delete, class:"btn btn-sm btn-danger destroy", "data-confirm" => "本当に削除しますか？" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class='container px-5 px-sm-0'>
    <div class='row'>
      <%= render "users/user_info2", user: @user, game: @game %>
      <div class='col-lg-7 offset-lg-1'>
        <h2>ユーザー一覧</h2>
        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th>ユーザー画像</th>
              <th>ユーザー名</th>
              <th colspan="1"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td>
                  <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: "jpeg", fallback: "no_image.jpg" %>
                </td>
                <td><%= user.name %></td>
                <td>
                  <%= link_to "詳細", user_path(user.id) %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @users %>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class='container px-5 px-sm-0'>
    <div class='row'>
      <%= render "users/user_info", user: @user, game: @game %>
      <div class='col-lg-7 offset-lg-1'>
        <%= render "games/game_index", games: @games, game: @game %>
      </div>
    </div>
  </div>
</main>